@startuml

title CVM-1\nLayered architecture\n

package "User Interface Layer" {
    [Display]
    [Keyboard]
    [TUI] #green
}

package "System Control Layer" {
    [FSM] #red
}

package "Subsystems Layer" {
    [Cola Dispenser]
    [Coin Acceptor]
}

package "Hardware Abstraction Layer = HAL" {
    [Hardware IO] #grey
}

[FSM] -down-> [Coin Acceptor]
[FSM] -down-> [Cola Dispenser]
[FSM] -up-> [Display]
[FSM] -up-> [Keyboard]
[FSM] -up-> [TUI]
[Coin Acceptor] --> [Hardware IO]
[Cola Dispenser] --> [Hardware IO]
[TUI] -down-> [Keyboard]
[TUI] -down-> [Display]
[Display] --> [Hardware IO]
[Keyboard] --> [Hardware IO]

@enduml
